apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: kwa9n6utz-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/kwa9n6utz-java-springboot-gitops